### PR TITLE
Add FFNx FF8Music mod

### PR DESCRIPTION
**Pull request by myst6re**

### CODE REVIEW

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
@myst6re can you please rebase your branch? I am not able for some reason to update the branch, it says I don't have the permission to do so. Thank you!

**Comment by myst6re** [comment]
> @myst6re can you please rebase your branch? I am not able for some reason to update the branch, it says I don't have the permission to do so. Thank you!

Done

**Comment by julianxhokaxhiu** [comment]
Thanks @myst6re sorry but we need another rebease if possible, should fix all the remaining CI issues. Sorry for the trouble

**Comment by julianxhokaxhiu** [comment]
Thanks a lot!

**Pull request merged**
